<a href="https://colab.research.google.com/github/sandesh611/Pytorch-Tutorial/blob/main/collab_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import numpy as np

In [3]:
#Lists
my_list = [[1,2,3,4],[6,7,8,9]]
my_list

[[1, 2, 3, 4], [6, 7, 8, 9]]

In [4]:
#NUMPY Array
np1 = np.random.rand(3,4)
np1

array([[0.68443002, 0.12196816, 0.70655716, 0.51647648],
       [0.42747591, 0.74863924, 0.70137522, 0.49746782],
       [0.74145755, 0.35408854, 0.87195502, 0.01936834]])

In [5]:
np1.dtype

dtype('float64')

In [6]:
#Tensors
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[ 0.4616,  1.5791, -0.9131, -0.4071],
        [-0.2929,  0.6454, -0.4397, -0.8555],
        [-1.0328,  0.5429,  0.4744,  0.3289]])

In [7]:
tensor_2d.dtype

torch.float32

In [8]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [9]:
#Create Tensor out of numpy_array
tensor_np = torch.tensor(np1)
tensor_np

tensor([[0.6844, 0.1220, 0.7066, 0.5165],
        [0.4275, 0.7486, 0.7014, 0.4975],
        [0.7415, 0.3541, 0.8720, 0.0194]], dtype=torch.float64)

In [3]:
#Tensor Operations

my_torch = torch.arange(20)
my_torch

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])

In [4]:
#Reshape
my_torch = my_torch.reshape(4,5)
my_torch

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])

In [8]:
my_torch2 = torch.arange(10)
my_torch2


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
#View
my_torch3 = my_torch2.view(2,5)
my_torch3

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [12]:
my_torch2[1] = 20;
my_torch2

tensor([ 0, 20,  2,  3,  4,  5,  6,  7,  8,  9])

In [13]:
my_torch3

tensor([[ 0, 20,  2,  3,  4],
        [ 5,  6,  7,  8,  9]])

In [14]:
#Slices
my_torch4 = my_torch3.reshape(5,2)
my_torch4

tensor([[ 0, 20],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]])

In [15]:
my_torch4[:1] #Fist row

tensor([[ 0, 20]])

In [36]:
my_torch4[0:,:-1]

tensor([[0],
        [2],
        [4],
        [6],
        [8]])